In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [3]:
a = np.array([])
print(a, type(a))

[] <class 'numpy.ndarray'>


In [6]:
a = np.array([1,2,3,4])
print(a, type(a))
print(a.dtype)
print(a.size)
print(a.itemsize)

[1 2 3 4] <class 'numpy.ndarray'>
int32
4
4


In [8]:
print(a.shape)
print(dir(a))

(4,)
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rls

In [14]:
mat = np.array([[1,2,3,4],[4,5,6]])
print(mat)
print(mat.size)
print(mat.shape)

[list([1, 2, 3, 4]) list([4, 5, 6])]
2
(2,)


In [24]:
a = np.arange(1,10)
print(a)
print(a.dtype)
print(type(a))
print(np.arange(10))
print(np.arange(10,20,2))
print(np.arange(10,20,2, dtype = 'f4'))

[1 2 3 4 5 6 7 8 9]
int32
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]
[10. 12. 14. 16. 18.]


In [26]:
z = np.zeros(5, dtype = np.int8)
print(z)
z = np.zeros((5,2), dtype = np.int8)
print(z)

[0 0 0 0 0]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [27]:
l = np.arange(1,100,10)
print(l)
l = np.linspace(1,80,10) #Automatically calculates the step size
print(l)

[ 1 11 21 31 41 51 61 71 81 91]
[ 1.          9.77777778 18.55555556 27.33333333 36.11111111 44.88888889
 53.66666667 62.44444444 71.22222222 80.        ]


In [31]:
n = np.random.randint(10)
print(n)
n = np.random.randint(10,15)
print(n)
n = np.random.randint(10,100,10)
print(n)

7
14
[60 14 13 79 52 53 77 55 62 63]
